pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Abhinavv-G/NGINX-Deployment-System.git'
            }
        }

        stage('Terraform Init') {
            steps {
                bat 'cd terraform && terraform init'
            }
        }

        stage('Terraform Validate') {
            steps {
                bat 'cd terraform && terraform validate'
            }
        }

        stage('Terraform Plan') {
            steps {
                bat 'cd terraform && terraform plan'
            }
        }

        stage('Terraform Apply') {
            steps {
                bat 'cd terraform && terraform apply -auto-approve'
            }
        }
    }
}